### ISSUE TITLE
[gtk3] "ls -l" output underlined, should disallow space in filename

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1163]
(Even with Quick Open disabled)

Execute `ls -l` and mouseover an entry that is newer than half year (showing hh:mm instead of year), e.g.

    drwxrwxrwt 16 root root 20480 Jan 25 01:19 tmp

Notice that up to (including) the timestamp it's all underlined.

I believe that the second regex of Quick Open assumes that this is a file named "drwxrwxrwt 16 root root 20480 Jan 25 01", and line 19.

Ctrl+click also prints silly things.

I think an easy and nice workaround could be to remove space from the allowed characters of filenames.

**Comment by Stibbons** [comment]
hello. This is a looooong time known issue of the quick open regex, on one hand quick open is really handy with the underlying of file name, and really useful in my daily workflow (and space in a file name happens, sadly), on the other hand there might have false positive :(

**Comment by egmontkob** [comment]
So, two things...

- These are underlined even if Quick Open is disabled, I'm wondering if the regexes could be uninstalled in this case.

- Having false positives every now and then is one thing, but when most of `ls -l`'s output is false positive then that's IMO way too much. I'm wondering if the issue could be mitigated. Let's say require in the regex that there are no two consecutive spaces. Or require that there's a dot in the filename. Or require that it doesn't end in digit... These are just a couple of ideas to consider, not sure what would be the best. :)

**Comment by gsemet** [comment]
fixed on HEAD (can you check?)

**Comment by egmontkob** [comment]
Not fixed for me, I can't see any change. (I can't see any potentially relevant commit either, the latest is dated Feb 12, I'm wondering if you forgot to git push??)
