### ISSUE TITLE
Exit freezes guake

### ISSUE THREAD

**Issue by KronwarsCZ** [Guake/guake#1330]
**Guake Version**: 3.0.5 - 1
**System**: Ubuntu 18.04 with GNOME 3.28

Whenever I type exit into guake the main tab freezes and can only close the drop-down terminal. If I want to use guake again I must kill it in other terminal.

**Comment by gsemet** [comment]
Should be fixed on HEAD

**Comment by KronwarsCZ** [comment]
I dont know what means HEAD, but I actually reinstalled guake just to update it and the problem is still there. What should I do?

**Comment by gsemet** [comment]
can you try installing from source code (HEAD means the current version of the source)

**Comment by Aaronik** [comment]
This bug was affecting me as well, running on a pretty clean Ubuntu 18.04 install. I haven't tried installing it from source, as I prefer to get my packages from the apt repos when I can, though I'm sure it'd work just fine. But another way to fix this, after reading the patch, is to install `libutempter0`.

`sudo apt-get install libutempter0` and the problem should go right away.

**Comment by fpohtmeh** [comment]
> `sudo apt-get install libutempter0` and the problem should go right away.
How about adding this dependency to Ubuntu package? It still freezes and isn't fixed
