### ISSUE TITLE
Search in terminal doesn't work

### ISSUE THREAD

**Issue by nibexo** [Guake/guake#1995]
Yesterday I installed on my Ubuntu 20.04.3 Guake and I have problem with search in terminal.
When I have some output in terminal and I press ctrl + shift + f, then I can see input for search text. Next I type some text to search but when I press Enter, nothing happens. Also when press buttons beside input then nothing happens and not go to searched text in terminal or highlight it.

**To Reproduce**

1. Open Guake
2. generate some output in Guake e.g. print some file 
3. press ctrl + shift + f
4. type some text (e,g first 3 letters of word which you know is in printed in Guake output)
5. press Enter

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - HPN HDMI-2
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		509 x 286 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by mlouielu** [comment]
Please update to latest Guake, fixed in >= 3.8.0.

**Comment by lsarni** [comment]
@mlouielu I'm on the latest version `guake is already the newest version (3.8.1-1~ppa~bionic2)` and the search still doesn't work.

**Comment by Davidy22** [comment]
Just to check, if you bind the same keybinding to something like open new tab, does it work? There is an issue from 3.8.1 fixed in 3.8.2 that may impact some keybindings

**Comment by mlouielu** [comment]
> @mlouielu I'm on the latest version `guake is already the newest version (3.8.1-1~ppa~bionic2)` and the search still doesn't work.

Could you please elaborate the step you use the search bar?

Can you also test it with next/prev button?

**Comment by lsarni** [comment]
@Davidy22 it doesn't let me set the keybinding
![image](https://user-images.githubusercontent.com/15196342/149317516-9ad31bed-a885-443f-95a6-7bcaeaad1ee7.png)

Not sure what you are trying to check, but with this set up Shift+Ctrl+F will open a new tab and Shift+Ctrl+A will open the search input but the search itself doesn't work (same result that with the default bindings)
![image](https://user-images.githubusercontent.com/15196342/149317768-8c4aa9da-3825-4a8a-b6dd-3aa1e4ef5f5e.png)

**Comment by lsarni** [comment]
@mlouielu I have the same problem as described on the original issue, the search input appears and I can write the search term but on enter or using the next/prev arrows nothing happens.

![image](https://user-images.githubusercontent.com/15196342/149318239-d53f7549-5c32-420a-99de-ee1b2c4a995f.png)

Here is the error
![image](https://user-images.githubusercontent.com/15196342/149318380-513d7797-72ea-4d81-93a4-9a36663c2f68.png)

**Comment by mlouielu** [comment]
As https://github.com/lanoxx/tilda/pull/399#issuecomment-548965346 point out, Ubuntu stop patching Vte from 19.04.

If you are welling to build Guake by yourself, you can remove PCRE2 flag, and the search function should work.

Or, maybe there is a Vte ppa that doesn't patch for this.

**Comment by Davidy22** [comment]
I suspect building vte yourself is rougher than the upgrade path from 18.04 to the next LTS, and there's probably some nice new stuff in 20.04
