### ISSUE TITLE
Guake multi-monitor placement / alignment issues in Ubuntu with Unity

### ISSUE THREAD

**Issue by hotice** [Guake/guake#395]
In Ubuntu 14.10 (and since there are only a few bug fixes in Ubuntu 14.10 compared to Ubuntu 14.04, I assume the same occurs in Ubuntu 14.04 LTS) with Unity, Guake 0.5.0 gets stuck on the second monitor if using anything other than the "always on primary" option and Guake shows up at least once on the second monitor.

For instance, after enabling "Appear on mouse display", if Guake shows up once on the second display, it then always shows up on the second display, no matter where the mouse is. Or if I set it to appear on the second display and then set it back to the first display, it continues to show up on the second display.

Also, when Guake (with center horizontal alignment and a 70 width value) shows up on the second monitor, it's aligned on the left and not in the center.

Let me know if you need further details.

**Comment by Stibbons** [comment]
Can someone reproduce on latest HEAD?

**Comment by hotice** [comment]
Tested using:
- Ubuntu 15.04 64bit with Unity, left Launcher set to always be visible
- latest Guake from Git with 70% width set in Guake
- 2 monitors

Results: the app works properly on the primary monitor but is always aligned to the left instead of being centered on the second monitor. I tested this with the "Appear on mouse display" enabled as well as with the option which allows setting Guake on one of the monitors only.

Also, in Guake's Preferences, on General, under "Main Window Horizontal Alignment", all the radio buttons seem enabled - is this normal? Maybe this has something to do with the app not being aligned correctly on the second monitor? Screenshot: http://i.imgur.com/9lT9E53.png

**Comment by Stibbons** [comment]
combobox issue fixed by c6c9099672a51518af81b679920317246421fdec

**Comment by hotice** [comment]
Unfortunately the combobox fix didn't solve the alignment issue.

**Comment by Stibbons** [comment]
indeed, that's why the ticket is still opened. I cannot easily work on it since I only have one screen :(

**Comment by ftonello** [comment]
I can still verify that the bug exists on Ubuntu 15.04 with guake 0.5.0-2.

**Comment by luccamendonca** [comment]
I can still verify that the bug exists on Ubuntu 15.10 with guake 0.8.4 (latest to the day, freshly compiled)

**Comment by gnuton** [comment]
This bug is still present in ubuntu 16.04 which ships guake 0.8.3

**Comment by Phiwa** [comment]
Any news on this? Running guake on Ubuntu 14.04 with two 24" displays.

**Comment by hotice** [comment]
This bug was fixed for me with Guake 0.8.6/0.8.7.

**Comment by Stibbons** [comment]
great news !

**Comment by Vizzard** [comment]
Unfortunately issue still present in Ubuntu 16.04 LTS with Guake 0.8.7 (full height, full width).

Guake works correctly if Unity Launcher is set to auto-hide. 
If Launcher is visible all the time Guake gets stuck on second monitor after opening it there for the first time. It's full width then. If I grab Guake window at the bottom and pull it up a little, then Guake is not full width but it follows mouse between monitors then (gap like in #565, only on second, right screen, main screen is always full width).

**Comment by mimf** [comment]
I'm also having this issue on Xubuntu 16.04. Guake is either aligned on one screen OR the other. 

The "Main window height" is not scalling properly on my laptop's screen. If I set it all the way to the maximum allowed value, I won't be able to see the tabs (which I've set at the bottom). This behaviour does not happen on my external monitor.
